wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.5
    start_time: 1675486502.468041
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.10.5
      5: 0.13.9
      8:
      - 2
      - 5
